name: build

on:
  pull_request: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - run: mvn verify javadoc:javadoc

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: target/site/apidocs
          TARGET_FOLDER: docs/latest/
          CLEAN: true
